In [1]:
import numpy as np

In [15]:
a =  np.array([1,2,3])
print(a)
b = np.array([[1,2,3,4],
            [5,6,7,8],
            [9,9,9,9]])
print(b)

[1 2 3]
[[1 2 3 4]
 [5 6 7 8]
 [9 9 9 9]]


In [4]:
a.itemsize

4

In [5]:
a.nbytes

12

In [10]:
np.ones((4,2,2), dtype='float64')

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [13]:
np.full((3,4),9,dtype = 'int32')

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [19]:
print(np.full(a.shape,9))
print(np.full_like(b,9))

[9 9 9]
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]


In [20]:
np.random.rand(5,3)

array([[0.54821515, 0.32197617, 0.44268885],
       [0.47666032, 0.72172952, 0.23905161],
       [0.05490819, 0.05921875, 0.0745172 ],
       [0.45450464, 0.06806302, 0.50574641],
       [0.14035759, 0.71193033, 0.35565189]])

In [22]:
np.random.random_sample(b.shape)

array([[0.51625113, 0.87560982, 0.7157892 , 0.60409679],
       [0.37612784, 0.8852101 , 0.11137439, 0.52518657],
       [0.3443025 , 0.28890397, 0.78882425, 0.22606408]])

In [27]:
np.random.randint(-99,100,size=(3,7))

array([[ 58, -96, -36,  42, -33,  67, -51],
       [-98,  93,  74, -36,  42, -56, -34],
       [-50, -59, -62, -42, -52, -85, -41]])

In [28]:
np.repeat(b,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8,
       8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9])

In [29]:
np.repeat(b,3,axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]])

In [32]:
np.repeat(b,3,axis=1)

array([[1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4],
       [5, 5, 5, 6, 6, 6, 7, 7, 7, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

### Crude Way

In [45]:
a = np.full((5,5),9)
for i in range(5):
    a[0][i] = 1
    a[i][0] = 1
    a[4][i] = 1
    a[i][4] = 1
for i in range(1,4):
    a[1][i] = 0
    a[i][1] = 0
    a[3][i] = 0
    a[i][3] = 0
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Better Way

In [58]:
a = np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [61]:
b = np.zeros((3,3))
b[1][1] = 9
print(b)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [65]:
a[1:-1,1:-1] = b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be careful with copying arrays

When you do b = a, both variables point to the same exact thing, so any changes in b will be reflected in a too.Use b = a.copy() then changes in each of them will be independent from each other.

In [71]:
a = np.ones((3,3))

In [72]:
b = a.copy()

In [74]:
a = np.zeros((3,3))
print(b)
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [1]:
import pandas as pd

In [9]:
df = pd.read_csv('titanic.csv')

In [10]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [15]:
df = pd.read_csv('titanic.csv', index_col = 'Name')

In [16]:
df

PassengerId  Survived  \
Name                                                                        
Braund, Mr. Owen Harris                                       1         0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...            2         1   
Heikkinen, Miss. Laina                                        3         1   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  4         1   
Allen, Mr. William Henry                                      5         0   
...                                                         ...       ...   
Montvila, Rev. Juozas                                       887         0   
Graham, Miss. Margaret Edith                                888         1   
Johnston, Miss. Catherine Helen "Carrie"                    889         0   
Behr, Mr. Karl Howell                                       890         1   
Dooley, Mr. Patrick                                         891         0   

                                                    Pclass     Sex   Age  \
Name                                                                       
Braund, Mr. Owen Harris                                  3    male  22.0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...       1  female  38.0   
Heikkinen, Miss. Laina                                   3  female  26.0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)             1  female  35.0   
Allen, Mr. William Henry                                 3    male  35.0   
...                                                    ...     ...   ...   
Montvila, Rev. Juozas                                    2    male  27.0   
Graham, Miss. Margaret Edith                             1  female  19.0   
Johnston, Miss. Catherine Helen "Carrie"                 3  female   NaN   
Behr, Mr. Karl Howell                                    1    male  26.0   
Dooley, Mr. Patrick                                      3    male  32.0   

                                                    SibSp  Parch  \
Name                                                               
Braund, Mr. Owen Harris                                 1      0   
Cumings, Mrs. John Bradley (Florence Briggs Tha...      1      0   
Heikkinen, Miss. Laina                                  0      0   
Futrelle, Mrs. Jacques Heath (Lily May Peel)            1      0   
Allen, Mr. William Henry                                0      0   
...                                                   ...    ...   
Montvila, Rev. Juozas                                   0      0   
Graham, Miss. Margaret Edith                            0      0   
Johnston, Miss. Catherine Helen "Carrie"                1      2   
Behr, Mr. Karl Howell                                   0      0   
Dooley, Mr. Patrick                                     0      0   

                                                              Ticket     Fare  \
Name                                                                            
Braund, Mr. Owen Harris                                    A/5 21171   7.2500   
Cumings, Mrs. John Bradley (Florence Briggs Tha...          PC 17599  71.2833   
Heikkinen, Miss. Laina                              STON/O2. 3101282   7.9250   
Futrelle, Mrs. Jacques Heath (Lily May Peel)                  113803  53.1000   
Allen, Mr. William Henry                                      373450   8.0500   
...                                                              ...      ...   
Montvila, Rev. Juozas                                         211536  13.0000   
Graham, Miss. Margaret Edith                                  112053  30.0000   
Johnston, Miss. Catherine Helen "Carrie"                  W./C. 6607  23.4500   
Behr, Mr. Karl Howell                                         111369  30.0000   
Dooley, Mr. Patrick                                           370376   7.7500   

                                                   Cabin Embarked  
Name                                                  